# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20, verbose_name='\u95ee\u5377ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u63d0\u95ee\u4ebaID')),
                ('title', models.CharField(default='-', max_length=50, verbose_name='\u95ee\u5377\u540d')),
                ('buildTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u95ee\u5377',
                'verbose_name_plural': '\u95ee\u5377',
            },
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretCode', models.CharField(max_length=100, verbose_name='\u968f\u673a\u7801')),
                ('pid', models.IntegerField(verbose_name='\u95ee\u5377ID')),
                ('mid', models.IntegerField(verbose_name='\u5f53\u524d\u9898\u76eeID')),
            ],
            options={
                'verbose_name': '\u51ed\u8bc1\u8868',
                'verbose_name_plural': '\u51ed\u8bc1\u8868',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=20, verbose_name='\u9898\u76eeID')),
                ('text', models.TextField(max_length=500, verbose_name='\u9898\u76ee\u5185\u5bb9')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m', verbose_name='\u4e0a\u4f20\u6587\u4ef6')),
                ('answers', models.CharField(max_length=300, verbose_name='\u9009\u9879')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Paper', verbose_name='\u95ee\u5377ID')),
            ],
            options={
                'verbose_name': '\u9898\u76ee',
                'verbose_name_plural': '\u9898\u76ee',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('password', models.CharField(max_length=256, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('wechat', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u5fae\u4fe1\u53f7')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m', verbose_name='\u5934\u50cf')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8868',
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
    ]
