# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.User', verbose_name='\u63d0\u95ee\u4eba'),
        ),
    ]
